### PR TITLE
Fix file identifier buffer overflow

### LINKED ISSUE #128: ps3netsrv buffer overflow
[core.12076.zip](https://github.com/aldostools/webMAN-MOD/files/1713869/core.12076.zip)

Linux  4.15.1-2-ARCH
Installed from https://aur.archlinux.org/packages/ps3netsrv

ps3netsrv /home/user/PS3/ps3netsrv/                                                                                          
ps3netsrv build 20170310 (mod by aldostools)                                                                                                
Path: /home/user/PS3/ps3netsrv

Waiting for client...
Connection from 192.168.0.195                                                                                                               
open /GAMES/Heavy.Rain.USA/PS3_GAME/ICON0.PNG                                                                                               
Connection from 192.168.0.195                                                                                                               
building virtual iso...                                                                                                                     
*** buffer overflow detected ***: ps3netsrv terminated                                                                                      
Aborted (core dumped)

coredumpctl info 12076:
```
       Message: Process 12076 (ps3netsrv) of user 1000 dumped core.

                Stack trace of thread 12414:
                #0  0x00007f75b7a1f860 raise (libc.so.6)
                #1  0x00007f75b7a20ec9 abort (libc.so.6)
                #2  0x00007f75b7a62437 __libc_message (libc.so.6)
                #3  0x00007f75b7af239f __GI___fortify_fail_abort (libc.so.6)
                #4  0x00007f75b7af23d1 __fortify_fail (libc.so.6)
                #5  0x00007f75b7af0260 __chk_fail (libc.so.6)
                #6  0x00007f75b7aef426 __stpcpy_chk (libc.so.6)
                #7  0x0000565070fa65cf n/a (ps3netsrv)
                #8  0x0000565070fa717a n/a (ps3netsrv)
                #9  0x0000565070fa7a07 n/a (ps3netsrv)
                #10 0x0000565070fa7bb5 n/a (ps3netsrv)
                #11 0x0000565070fa44fc n/a (ps3netsrv)
                #12 0x00007f75b7fc008c start_thread (libpthread.so.0)
                #13 0x00007f75b7ae0e7f __clone (libc.so.6)

                Stack trace of thread 12076:
                #0  0x00007f75b7fc9cab accept (libpthread.so.0)
                #1  0x0000565070fa2df9 n/a (ps3netsrv)
                #2  0x00007f75b7a0bf4a __libc_start_main (libc.so.6)
                #3  0x0000565070fa32ca n/a (ps3netsrv)
```

coredumpctl gdb 12076 
and bt:
```
Reading symbols from /usr/bin/ps3netsrv...(no debugging symbols found)...done.
[New LWP 12414]
[New LWP 12076]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `ps3netsrv /home/user/PS3/ps3netsrv/'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f75b7a1f860 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f75b639b700 (LWP 12414))]
(gdb) bt
#0  0x00007f75b7a1f860 in raise () from /usr/lib/libc.so.6
#1  0x00007f75b7a20ec9 in abort () from /usr/lib/libc.so.6
#2  0x00007f75b7a62437 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f75b7af239f in __fortify_fail_abort () from /usr/lib/libc.so.6
#4  0x00007f75b7af23d1 in __fortify_fail () from /usr/lib/libc.so.6
#5  0x00007f75b7af0260 in __chk_fail () from /usr/lib/libc.so.6
#6  0x00007f75b7aef426 in __stpcpy_chk () from /usr/lib/libc.so.6
#7  0x0000565070fa65cf in ?? ()
#8  0x0000565070fa717a in ?? ()
#9  0x0000565070fa7a07 in ?? ()
#10 0x0000565070fa7bb5 in ?? ()
#11 0x0000565070fa44fc in ?? ()
```

### PR DESCRIPTION
**Pull request by mkroening**
Fixes #128
This ensures that the string concatenation takes place in a big enough buffer (for the compiler to notice).

### CODE REVIEW

File: _Projects_/ps3netsrv/src/VIsoFile.cpp [hunk 1]
```diff
@@ -793,19 +793,18 @@ bool VIsoFile::buildContent(DirList *dirList, bool joliet)
...
 			char *fileName = strrchr(fileList->path, '/') + 1;
 
+			char *s = new char[strlen(fileName) + 3];
+			strcpy(s, fileName);
+			strcat(s, ";1");
 			if (!joliet)
 			{
-				record->len_fi = strncpy_upper(&record->fi, fileName, MAX_ISONAME - 2) + 2;
-				strcat(&record->fi, ";1");
+				record->len_fi = strncpy_upper(&record->fi, s, MAX_ISONAME - 2);
```
Comment (aldostools) [inline _Projects_/ps3netsrv/src/VIsoFile.cpp:801]: I think the max size of the copy should be MAX_ISONAME (without -2)
record->len_fi = strncpy_upper(&record->fi, s, MAX_ISONAME);

However, with this new logic there are scenarios where the file name (char *s) could be truncated (if length of s larger than MAX_ISONAME), and the string ";1" would be missing in record->fi.

In the previous logic, the string ";1" would be always appended, even if the file name is truncated.

**Comment by mkroening** [comment]
@aldostools, what do you think?

**Review by aldostools — COMMENTED** [review]
> @aldostools, what do you think?

I think this code will have some issues when the file name exceed the size of MAX_ISONAME 

See me previous comments. Anyway I will merge your pull.
